### ISSUE TITLE
Error with click python library in imgtool.py

### ISSUE THREAD

**Issue by tito97sp** [mcu-tools/mcuboot#1223]
**Brief**
When **imgtool.py** is launch inside a docker container with ubuntu (tested in ubuntu18.04), the application fails as it has not the following variables exported:

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

**Error:**
Traceback (most recent call last):
  File "/__w/project_template/project_template/build/stm_nucleo_h743zi_main/NuttX/apps/boot/mcuboot/mcuboot/scripts/imgtool.py", line 22, in <module>
    main.imgtool()
  File "/github/home/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/github/home/.local/lib/python3.6/site-packages/click/core.py", line 1034, in main
    _verify_python_env()
  File "/github/home/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 100, in _verify_python_env
    raise RuntimeError("\n\n".join(extra))
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

**Comment by d3zd3z** [comment]
Is there something to be fixed in imgtool? It looks like the command parsing library requires the locale be properly configured. I would expect numerous programs to also require that to be the case.
